### PR TITLE
pull

### PR DESCRIPTION
**Pull request by techguy16**

### CODE REVIEW

**Comment by techguy16** [comment]
It fixes some issues with gdevd.

**Comment by R1tschY** [comment]
Can you please resolve the conflicts.

**Comment by techguy16** [comment]
Hi @R1tschY ,
I've fixed the conflicts between the two branches. It is OK to merge.

**Comment by R1tschY** [comment]
All fixes are already in the master branch. The only addition in this pull request is the `rustup-install.sh` script. But I do not want to maintain this script and also I do not know of any other Rust project that is maintaining a `rustup-install.sh` in the project repository. In the README there is already a link to the official website where it is described how to install the Rust toolchain. This is from my point of view enough to build the project.

**Comment by techguy16** [comment]
@R1tschY when I made this PR it was when you hadn't made any changes since the original and you had to use dbus-tree to get it working. Sorry about it.

**Pull request closed without merging**
